### ISSUE TITLE
A Question about FGO (China or Taiwanese)

### ISSUE THREAD

**Issue by darkzamurai** [Renari/Fate-Grand-Order-Translation#12]
Hello sorry if I something disturbed or bother about a long time failed translation patch if you can patch the Chinese version or the Taiwanese version.... If you can not to do something can you teach me how did you translate the game itself......

**Comment by darkzamurai** [comment]
@renari hello?

**Comment by Renari** [comment]
I don't have the time to teach you how to reverse engineer applications. You're better of studying computer science and learning how your computer works on a low level.

**Comment by darkzamurai** [comment]
Oh you did reply..... i don't precise teach or fully teach me but few infos what i need just to make it short only thats what i want if you can't teach me well..... Sorry to be bother on you.....

**Comment by darkzamurai** [comment]
:-( I guess I wait two months on US release rather than the owner of this repository that abandoned and not to continue it and also can't delete this some players teased with your failed and lame translation.....

**Comment by Renari** [comment]
I don't take insults lightly, you're aware how much time this takes right? It took me two months to do what I did do, two months of actively working on this every day. I'm a university student and I don't have that kind of time to be spending on this. The translation ultimately failed because I was not confident in my ability to produce accurate translations and there didn't seem to be anyone interested in helping. Thus I decided to stop maintaining the project. Now please excuse me while I prepare for my finals.

**Comment by nicex000** [comment]
FailFish
